# -*- coding: utf-8 -*-
"""Firstipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yGDm-DpltppFXl4HUas43uDREZdtdqVf
"""

def factorial(n):
    if n == 0 or n == 1:
        return 1
    else:
        return n * factorial(n - 1)

# Example usage
num = int(input("Enter a number: "))
print("Factorial of", num, "is", factorial(num))

