# -*- coding: utf-8 -*-
"""Second.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1edKE2Gm3wKL-zIIh0BxKX21DhebhYQRo
"""

def fibonacci(n):
    fib_sequence = []
    a, b = 0, 1
    while len(fib_sequence) < n:
        fib_sequence.append(a)
        a, b = b, a + b
    return fib_sequence

# Example usage
num_terms = int(input("Enter the number of Fibonacci terms to generate: "))
if num_terms <= 0:
    print("Please enter a positive integer.")
else:
    print("Fibonacci sequence:", fibonacci(num_terms))